--------------------------------------------------------------------------------
-- Copyright © 2025+ Eamonn Anthony Duffy. All Rights Reserved.
--------------------------------------------------------------------------------
--
-- Version: V1.0.0.
--
-- Created: Eamonn A. Duffy, 6-June-2025.
--
-- Updated: Eamonn A. Duffy, 1-August-2026.
--
-- Purpose: Forward Script for the Main SQL for the Central Security Service PostgreSQL Database.
--
-- Assumptions:
--
--  0.  The PostgreSQL database has already been created and the target schema is selected.
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Begin the Main Transaction.
--------------------------------------------------------------------------------

BEGIN TRANSACTION;

--------------------------------------------------------------------------------
-- Create Schema if/as appropriate.
--------------------------------------------------------------------------------

CREATE SCHEMA IF NOT EXISTS "Dad";

--------------------------------------------------------------------------------
-- Create the Unique Reference Id Sequence if/as appropriate.
--------------------------------------------------------------------------------

CREATE SEQUENCE IF NOT EXISTS "Dad"."UniqueReferenceId" AS bigint MINVALUE 0 START WITH 0 INCREMENT BY 1;

--------------------------------------------------------------------------------
-- Create Tables if/as appropriate.
--------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "Dad"."CentralSecurityServiceDatabaseVersions"
(
    "DatabaseVersionId" integer GENERATED BY DEFAULT AS IDENTITY (MINVALUE 0 START WITH 0 INCREMENT BY 1) PRIMARY KEY,
    "Major" integer NOT NULL,
    "Minor" integer NOT NULL,
    "Patch" integer NOT NULL,
    "Build" varchar(128) NOT NULL,
    "Description" varchar(256) NOT NULL,
    "CreatedDateTimeUtc" timestamptz NOT NULL DEFAULT (CLOCK_TIMESTAMP() AT TIME ZONE 'UTC'),
    "LastUpdatedDateTimeUtc" timestamptz NULL,

    CONSTRAINT "UX_Dad_CentralSecurityServiceDatabaseVersions_Version" UNIQUE ("Major", "Minor", "Patch", "Build")
);

CREATE TABLE IF NOT EXISTS "Dad"."ReferenceTypes"
(
    "ReferenceTypeId" smallint NOT NULL PRIMARY KEY,
    "ReferenceType" varchar(128) NOT NULL,
    "CreatedDateTimeUtc" timestamptz NOT NULL DEFAULT (CLOCK_TIMESTAMP() AT TIME ZONE 'UTC'),
    "LastUpdatedDateTimeUtc" timestamptz NULL
);

INSERT INTO "Dad"."ReferenceTypes" ("ReferenceTypeId", "ReferenceType")
VALUES
    (0, 'Image'),
    (1, 'Video Url'),
    (2, 'Url')
ON CONFLICT ("ReferenceTypeId") DO NOTHING;

CREATE TABLE IF NOT EXISTS "Dad"."References"
(
    "ReferenceId" bigint GENERATED BY DEFAULT AS IDENTITY (MINVALUE 0 START WITH 0 INCREMENT BY 1) PRIMARY KEY,
    "UniqueReferenceId" bigint NOT NULL,
    "SubReferenceId" integer NOT NULL,
    "Redacted" boolean NOT NULL DEFAULT FALSE,
    "ReferenceTypeId" smallint NOT NULL REFERENCES "Dad"."ReferenceTypes" ("ReferenceTypeId"),
    "ThumbnailFileName" varchar(512) NULL,
    "ReferenceName" varchar(512) NOT NULL,
    "Description" varchar(512) NULL,
    "Categorisations" varchar(512) NOT NULL,
    "Annotations" varchar(512) NULL,
    "CreatedDateTimeUtc" timestamptz NOT NULL DEFAULT (CLOCK_TIMESTAMP() AT TIME ZONE 'UTC'),
    "LastUpdatedDateTimeUtc" timestamptz NULL,

    CONSTRAINT "UX_Dad_References_ReferenceIds" UNIQUE ("UniqueReferenceId", "SubReferenceId")
);

CREATE INDEX IF NOT EXISTS "IX_Dad_References_UniqueReferenceId"
    ON "Dad"."References" ("UniqueReferenceId", "SubReferenceId");

--------------------------------------------------------------------------------
-- Insert Version.
--------------------------------------------------------------------------------

INSERT INTO "Dad"."CentralSecurityServiceDatabaseVersions"
    ("Major", "Minor", "Patch", "Build", "Description")
VALUES
    (1, 0, 0, '0', 'Beta Build.')
ON CONFLICT ("Major", "Minor", "Patch", "Build") DO NOTHING;

--------------------------------------------------------------------------------
-- End.
--------------------------------------------------------------------------------

COMMIT TRANSACTION;

--------------------------------------------------------------------------------
-- End Of File.
--------------------------------------------------------------------------------

/*

SELECT nextval('"Dad"."UniqueReferenceId"');

ALTER SEQUENCE "Dad"."UniqueReferenceId" RESTART WITH 0;

ROLLBACK TRANSACTION;

*/
